const root=document.querySelector('#root');
const devices=[{name:'キッチン下',temp:27.8,humidity:68,detections:[0,1,0,2,0,1,3],score:87,battery:100,risk:'高'},{name:'洗面台下',temp:25.2,humidity:73,detections:[0,0,1,0,0,0,1],score:75,battery:68,risk:'中'},{name:'冷蔵庫横',temp:28.4,humidity:62,detections:[1,0,0,1,2,0,2],score:82,battery:82,risk:'中'},{name:'リビング',temp:24.1,humidity:48,detections:[0,0,0,0,0,0,0],score:92,battery:91,risk:'低'}];
const state={device:0,period:'24時間',place:0,read:false,filter:'すべて',replaced:{},ac:true,purifier:true,temp:24,acMode:'自動',fan:'自動',layer:true,floor:1};
const paths={mini:[['home','ホーム'],['climate','温湿度'],['history','検知履歴'],['alerts','通知']],placement:[['map','設置マップ'],['photos','撮影画像'],['floor','再現間取り']],house:[['dashboard','全体'],['devices','mini管理'],['control','家電連携']]};
const names={mini:'AI Home Doctor Mini',placement:'設置位置ナビ',house:'AIホームドクター'};
const places=[{name:'キッチン・シンク下',risk:'高',reason:'配管まわりの隙間と水気があるため、侵入と滞留を見守る優先位置です。',position:'配管の手前・床面',x:'24%',y:'57%'},{name:'冷蔵庫の横',risk:'中',reason:'家電の放熱と狭い隙間を確認する位置です。通気口をふさがない場所に置きます。',position:'冷蔵庫横の壁際',x:'70%',y:'32%'},{name:'洗面台の下',risk:'中',reason:'排水管まわりの湿気と侵入経路を見守る位置です。水が直接かからない場所に置きます。',position:'排水管の近く・床面',x:'55%',y:'58%'}];

function icon(name){
 const paths={home:'M3 10 12 3 21 10V21H3Z',check:'m5 12 4 4L19 6',alert:'M12 3 22 21H2ZM12 9v5m0 3v1',clock:'M12 6v6l4 2M22 12a10 10 0 1 1-20 0 10 10 0 0 1 20 0',drop:'M12 2C9 7 4 11 4 15a8 8 0 0 0 16 0C20 11 15 7 12 2Z',temp:'M9 14V5a3 3 0 0 1 6 0v9a5 5 0 1 1-6 0ZM12 7v10',sensor:'M12 12h.01M8 8a6 6 0 0 0 0 8m8-8a6 6 0 0 1 0 8M4 4a12 12 0 0 0 0 16M20 4a12 12 0 0 1 0 16',bug:'M8 9h8v7a4 4 0 0 1-8 0ZM9 9V6h6v3M5 7l3 3m8 0 3-3M3 14h5m8 0h5M5 21l4-3m6 0 4 3M10 3l2 3 2-3',air:'M3 7h12a3 3 0 1 0-3-3M2 12h17a3 3 0 1 1-3 3M4 17h5',power:'M12 2v10M6 5a9 9 0 1 0 12 0'};
 return `<svg class="ui-icon" viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"><path d="${paths[name]||paths.home}"/></svg>`;
}
function detectionChart(d){
 return `<div class="panel detection-chart"><div class="row"><h2>${icon('sensor')} 赤外線検知の推移</h2><small>過去7日間</small></div><svg class="chart" viewBox="0 0 520 170" role="img" aria-label="日別の赤外線検知回数。${d.detections.join(',')}回"><path class="grid" d="M35 30H500M35 75H500M35 120H500"/><text x="5" y="35">4回</text><text x="5" y="80">2回</text><text x="12" y="124">0</text>${d.detections.map((v,i)=>`<rect x="${53+i*64}" y="${120-v*22.5}" width="26" height="${Math.max(v*22.5,2)}" rx="4" fill="${v>2?'#dfa635':'#399b69'}"/><text x="${63+i*64}" y="${110-v*22.5}" text-anchor="middle">${v}</text><text x="${66+i*64}" y="145" text-anchor="middle">9/${7+i}</text>`).join('')}</svg><a class="text-link" href="#mini/history">検知時刻と履歴を見る →</a></div>`;
}
function overviewCharts(){
 const values=[76,79,77,80,78,79,82];
 return `<div class="grid2 overview-charts"><div class="panel"><div class="row"><h2>${icon('home')} 健康度の推移</h2><span class="badge">${icon('check')} +3</span></div><svg class="chart" viewBox="0 0 340 175" role="img" aria-label="総合健康度 過去7日間:76,79,77,80,78,79,82点"><path class="grid" d="M35 30H320M35 80H320M35 130H320"/><text x="4" y="34">90</text><text x="4" y="84">80</text><text x="4" y="134">70</text><polygon points="35,130 ${values.map((v,i)=>`${35+i*47},${130-(v-70)*5}`).join(' ')} 317,130" fill="#e3f3eb"/><polyline class="temperature" points="${values.map((v,i)=>`${35+i*47},${130-(v-70)*5}`).join(' ')}"/>${values.map((v,i)=>`<circle cx="${35+i*47}" cy="${130-(v-70)*5}" r="4" fill="#399b69"/><text x="${35+i*47}" y="155" text-anchor="middle">9/${7+i}</text>`).join('')}</svg></div><div class="panel"><h2>${icon('home')} 部屋別の健康度</h2>${devices.map(d=>`<div class="score-bar"><span>${d.name}</span><div><i style="width:${d.score}%;background:${d.score<80?'#dfa635':'#399b69'}"></i></div><b>${d.score}</b></div>`).join('')}<small>各miniのスコア / 100点</small></div></div>`;
}

function route(){const [group,page]=location.hash.slice(1).split('/');return paths[group]?{group,page:paths[group].some(x=>x[0]===page)?page:paths[group][0][0]}:{group:null};}
function badge(t){const warning=/高|注意|未読/.test(t), mid=/中|参考/.test(t);return `<span class="badge ${warning?'high':mid?'medium':''}">${icon(warning?'alert':mid?'clock':'check')}${t}</span>`;}
function metric(label,value,sub=''){return `<div class="metric">${icon(label.includes('湿度')?'drop':label.includes('温度')?'temp':label.includes('家電')?'power':label.includes('注意')?'alert':'home')}<small>${label}</small><b>${value}</b><small>${sub}</small></div>`;}
function head(kicker,title,extra=''){return `<div class="page-head"><div><span class="eyebrow">${kicker}</span><h1>${title}</h1></div>${extra}</div>`;}
function ring(value){return `<div class="ring" style="--score:${value}"><div><b>${value}</b><small>/ 100</small></div></div>`;}
function modal(title,body){document.querySelector('#detailBody').innerHTML=`<h2>${title}</h2>${body}`;document.querySelector('#detail').showModal();}
function toast(message){const t=document.querySelector('#toast');t.textContent=message;t.style.display='block';clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.style.display='none',3000);}
function roomArt(n){return `<img class="room-image" src="assets/${roomFiles[n]}.png" alt="${roomNames[n]}の写真風生成画像" loading="lazy">`;}
function launcher(){return `<main id="content" class="container"><div class="intro"><div><span class="eyebrow">HOME DOCTOR / DEMO STUDIO</span><h1>見えないリスクを、<br><em>見える安心へ。</em></h1><p class="muted">住まいを見守り、最適な場所を見つけ、家全体を整える。<br>3つのデモから、HomeDoctorのある暮らしを体験。</p></div><div class="device-art product-photo"><img src="assets/homedoctor-mini.png" alt="PDF P.5のHomeDoctor mini製品写真"><span>HomeDoctor mini</span></div></div><div class="row"><span class="eyebrow">CHOOSE YOUR EXPERIENCE</span><small>03 DEMOS</small></div><div class="cards" style="margin-top:20px">${[['mini/home','01','◉','害虫リスクを見守る','HomeDoctor Mini','温湿度、赤外線検知、交換管理。キッチン下から始める住環境モニタリング。'],['placement/map','02','⌖','最適な場所を見つける','設置位置ナビ','撮影した部屋を間取りに。リスクと設置位置を、ひとつのマップで確認。'],['house/dashboard','03','⌂','家全体の健康を整える','統合ダッシュボード','複数のminiをつなぎ、住まいを可視化。エアコンや空気清浄機も一緒に管理。']].map(([url,n,icon,k,t,p])=>`<a class="demo-card" href="#${url}"><div class="card-num"><span>DEMO ${n}</span><span>${k}</span></div><div class="card-symbol">${icon}</div><h2>${t}</h2><p>${p}</p><div class="card-link">デモを体験する <span>↗</span></div></a>`).join('')}</div><p class="footnote">デモ用のサンプルデータです。実機・家電への接続や画像の送信は行いません。</p></main>`;}
function mini(page){const d=devices[state.device];const select=`<select id="deviceSelect" aria-label="設置場所">${devices.map((x,i)=>`<option value="${i}" ${i===state.device?'selected':''}>${x.name}</option>`).join('')}</select>`;
if(page==='home')return head('PHASE 1 / MONITORING','住まいを見守る',select)+`<div class="panel hero"><div><small>${d.name} · 最終更新 09:41</small><h2>今日も、見守っています。</h2><p>HOME SCORE · 総合スコア<br>個別リスクもあわせて確認しましょう。</p></div>${ring(d.score)}</div><div class="grid2">${[['害虫・侵入リスク',d.risk,'history','赤外線検知から確認'],['室内・カビリスク',d.humidity>70?'高':'低','climate','温湿度の変化を確認'],['ダニリスク','中','climate','環境リスクを確認'],['換気・乾燥度','良好','climate','過去24時間の推移']].map(([t,r,p,s])=>`<a class="metric risk-link" href="#mini/${p}"><span class="status-symbol">${icon(t.includes('害虫')?'bug':t.includes('カビ')?'drop':t.includes('ダニ')?'alert':'air')}</span>${badge(r)}<strong>${t}</strong><small>${s} →</small></a>`).join('')}</div><h2 class="section-title">環境モニタリング</h2><div class="grid3">${metric('温度',d.temp+'℃')+metric('湿度',d.humidity+'%')+`<a class="metric infrared-link" href="#mini/history">${icon('sensor')}<small>赤外線検知 / 今日</small><b>${d.detections[6]}回</b><small>検知履歴を見る →</small></a>`}</div>${detectionChart(d)}<p class="tip"><strong>✦ 今日のチェックポイント</strong>${d.name}の湿気と配管まわりを確認しましょう。<a href="#mini/alerts">お知らせを見る →</a></p>`;
if(page==='climate')return climateScreen(d,select);
if(page==='history')return head('INFRARED SENSOR','検知履歴と交換管理',select)+`${detectionChart(d)}<div class="panel"><div class="row"><h2>赤外線による侵入検知</h2>${badge('監視中')}</div><div class="segmented">${['すべて','検知あり'].map(x=>`<button data-filter="${x}" class="${state.filter===x?'selected':''}">${x}</button>`).join('')}</div>${[...(d.detections[6]?[['09/13 02:14','移動体を検知',`赤外線センサー反応 · ${d.detections[6]}回`]]:[]),...(d.detections[5]?[['09/12 23:48','移動体を検知',`赤外線センサー反応 · ${d.detections[5]}回`]]:[]),['09/12 09:41','検知なし','定時モニタリング']].filter(x=>state.filter==='すべて'||x[1]!=='検知なし').map(([t,n,s])=>`<div class="list-row"><span class="circle-icon">${icon(n==='検知なし'?'check':'sensor')}</span><div class="grow"><time>${t}</time><p><strong>${n}</strong> · ${d.name}</p><small>${s}</small></div></div>`).join('')}<p class="screen-note">赤外線の反応のみでは害虫の種類は確定しません。</p></div><div class="panel"><small>BLACK CAP / 交換管理</small><h2 style="margin-top:12px">${state.replaced[state.device]?'交換を記録しました':'交換予定まで、あと23日'}</h2><p>設置場所：${d.name}<br>交換予定：${state.replaced[state.device]?'2027年9月13日':'2026年10月6日'}</p><div class="progress"><i style="width:${state.replaced[state.device]?1:94}%"></i></div><div class="row"><button class="secondary" data-info="replacement">交換について</button><button class="btn" data-replace>${state.replaced[state.device]?'記録済み':'交換済みにする'}</button></div><p class="screen-note">交換予定日はデモの設定値です。実際は製品表示の使用期間に従ってください。</p></div>`;
return head('NOTIFICATIONS','住まいからのお知らせ',`<button class="secondary" data-read>${state.read?'すべて既読':'すべて既読にする'}</button>`)+[['侵入を検知しました','キッチン下で02:14に赤外線センサーが反応しました。履歴と周辺の状態を確認してください。','history','09/13 02:14'],['湿度が低下しました','キッチン下の湿度が70%未満に下がりました。過去3週間の高湿度を踏まえ、周辺の湿気やカビの兆候を確認しましょう。','climate','09/10 09:00'],['ブラックキャップの交換予定','交換予定まであと23日です。設置場所と予定日を確認できます。','history','09/12 09:00']].sort((a,b)=>b[3].localeCompare(a[3])).map(([t,p,url,time])=>`<article class="panel notice ${state.read?'':'unread'}"><div class="row"><small>${time}</small>${state.read?'':badge('未読')}</div><h2>${t}</h2><p>${p}</p><a class="secondary" href="#mini/${url}">詳細を見る →</a></article>`).join('')+humidityNotifications();}
function placement(page){return richPlacement(page);}
function house(page){if(page==='devices')return head('DEVICE MANAGEMENT','HomeDoctor miniの状態')+`<div class="panel"><div class="row"><h2>接続済みのmini</h2>${badge('4台オンライン')}</div>${devices.map((d,i)=>`<div class="list-row"><span class="circle-icon">${icon('sensor')}</span><div class="grow"><strong>${d.name}</strong><p>HDM-00${i+1} · Wi-Fi接続中</p><small>${d.temp}℃ / ${d.humidity}% · 電池 ${d.battery}%</small></div><button class="secondary" data-device-detail="${i}">詳細</button></div>`).join('')}</div><p class="tip"><strong>すべてのminiが正常に通信しています</strong>各部屋の詳細から、環境値・通信・電池の状態を確認できます。</p>`;
if(page==='control')return head('CONNECTED APPLIANCES','家電をコントロール')+`<div class="grid2 appliance-grid"><div class="panel appliance"><div class="row"><div><small>リビング</small><h2>${icon('air')} エアコン</h2></div><button class="switch" role="switch" aria-label="エアコン電源" aria-checked="${state.ac}" data-power="ac"></button></div><div class="${state.ac?'':'offline'}"><div class="temp-control"><button data-temp="-1" aria-label="設定温度を下げる" ${!state.ac||state.temp===18?'disabled':''}>−</button><span><b>${state.temp}</b>℃</span><button data-temp="1" aria-label="設定温度を上げる" ${!state.ac||state.temp===30?'disabled':''}>＋</button></div><label>運転モード<select data-mode="acMode" ${state.ac?'':'disabled'}>${['自動','冷房','除湿','暖房','送風'].map(m=>`<option ${state.acMode===m?'selected':''}>${m}</option>`).join('')}</select></label></div><p class="screen-note">${state.ac?'運転中':'停止中'} · 設定はこのデモ内のみ反映</p></div><div class="panel appliance"><div class="row"><div><small>リビング</small><h2>${icon('air')} 空気清浄機</h2></div><button class="switch" role="switch" aria-label="空気清浄機電源" aria-checked="${state.purifier}" data-power="purifier"></button></div><div style="padding:30px 0;text-align:center"><span class="eyebrow">AIR QUALITY</span><h2 style="font-size:35px;margin:10px">良好</h2><small>VOC 低 · サンプル環境値</small></div><label>風量<select data-mode="fan" ${state.purifier?'':'disabled'}>${['自動','静音','標準','強'].map(m=>`<option ${state.fan===m?'selected':''}>${m}</option>`).join('')}</select></label><p class="screen-note">${state.purifier?'運転中':'停止中'} · 設定はこのデモ内のみ反映</p></div></div><p class="tip"><strong>住まいの状態を見ながら操作</strong>環境モニタリングと家電をひとつの画面で扱うデモです。実際の機器は動作しません。</p>`;
return head('WHOLE HOME / OVERVIEW','住まい全体の健康度',badge('4台 同期済み'))+`<div class="panel hero"><div><small>HOME HEALTH SCORE</small><h2>今日の住まいは概ね良好</h2><p>複数のminiの情報をまとめて確認。<br>水まわりの湿気に注意ポイントがあります。</p></div>${ring(82)}</div><div class="grid3">${metric('接続中のmini','4台')+metric('注意ポイント','2件')+metric('連携家電','2台')}</div>${overviewCharts()}<h2 class="section-title">住まいの健康状態</h2><div class="grid2">${[['快適性','良好','室温24.1℃ / 湿度48%'],['空気の健康度','良好','VOC 低 / CO₂ 620ppm'],['カビ・結露リスク','注意','洗面台下の湿気を確認'],['害虫リスク','注意','キッチン下に赤外線反応'],['住宅劣化リスク','参考','長期モニタリングのイメージ'],['エネルギー効率','良好','省エネ運転のイメージ']].map(([n,r,s])=>`<div class="metric health-row-card"><span class="status-symbol">${icon(n.includes('空気')?'air':n.includes('カビ')?'drop':n.includes('害虫')?'bug':n.includes('劣化')?'alert':n.includes('エネルギー')?'power':'home')}</span><div><strong>${n}</strong><small>${s}</small></div>${badge(r)}</div>`).join('')}</div><h2 class="section-title">部屋ごとの状態</h2><div class="panel">${devices.map((d,i)=>`<div class="list-row"><div class="grow"><strong>${d.name}</strong><p>${d.temp}℃ / ${d.humidity}%</p></div><div class="room-score"><strong>${d.score}<small> /100</small></strong><div class="progress"><i style="width:${d.score}%"></i></div></div><button class="secondary" data-device-detail="${i}">詳細</button></div>`).join('')}</div><a class="btn" href="#house/control">連携家電を操作する →</a>`;}
function render(){const {group,page}=route();document.title=(group?names[group]:'HomeDoctor Demo Studio')+'｜デモ';root.innerHTML=`<header class="site"><a class="logo" href="#"><i>＋</i>AI HomeDoctor</a></header>`+(group?`<div class="workspace"><aside><a class="back" href="#">← デモ一覧</a><div class="side-title">${names[group]}</div>${paths[group].map(([p,n])=>`<a href="#${group}/${p}" class="${p===page?'active':''}" ${p===page?'aria-current="page"':''}>${n}</a>`).join('')}<div class="side-mini">HomeDoctor mini<br>住まいの小さな変化を、<br>毎日の安心につなげる。</div></aside><main id="content" class="content">${group==='mini'?mini(page):group==='placement'?placement(page):house(page)}<p class="footnote">DEMO · 表示値、解析結果、履歴はすべてサンプルです。</p></main></div>`:launcher());}
root.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;let rerender=true;if(b.dataset.climateEvent){state.device=0;state.period='1カ月';location.hash='mini/climate';window.scrollTo(0,0);}else if(b.dataset.floor){state.floor=Number(b.dataset.floor);state.place=state.floor===1?0:3;}else if(b.dataset.period)state.period=b.dataset.period;else if(b.dataset.filter)state.filter=b.dataset.filter;else if(b.dataset.place!==undefined)state.place=Number(b.dataset.place);else if(b.hasAttribute('data-layer'))state.layer=!state.layer;else if(b.hasAttribute('data-read')){state.read=true;toast('すべてのお知らせを既読にしました');}else if(b.dataset.power){state[b.dataset.power]=!state[b.dataset.power];toast('デモ内の運転状態を変更しました');}else if(b.dataset.temp)state.temp=Math.max(18,Math.min(30,state.temp+Number(b.dataset.temp)));else if(b.dataset.photo!==undefined){const n=Number(b.dataset.photo);modal(roomNames[n]+'の撮影サンプル',roomArt(n)+'<p>画像から家具、水まわり、壁の位置を認識する体験です。このデモは写真風のAI生成画像を使っています。</p>');rerender=false;}else if(b.dataset.deviceDetail!==undefined){const d=devices[Number(b.dataset.deviceDetail)];modal(d.name+' mini',`<p>状態：オンライン / Wi-Fi接続<br>温度：${d.temp}℃<br>湿度：${d.humidity}%<br>赤外線検知：本日${d.detections[6]}回<br>電池残量：${d.battery}%<br>最終同期：09:41</p>`);rerender=false;}else if(b.dataset.info){modal('交換時期の管理','<p>使用するブラックキャップの製品表示に従って交換してください。デモでは設置日からの交換予定を表示しています。</p>');rerender=false;}else if(b.hasAttribute('data-replace')){modal('交換を記録',`<p>${devices[state.device].name}の交換日を2026年9月13日として記録します。</p><button class="btn" id="confirmReplace">この日付で記録する</button>`);rerender=false;}else rerender=false;if(rerender){const key=[...b.attributes].find(a=>a.name.startsWith('data-'));render();if(key)root.querySelector(`button[${key.name}="${key.value}"]`)?.focus({preventScroll:true});}});
root.addEventListener('change',e=>{if(e.target.id==='deviceSelect'){state.device=Number(e.target.value);render();document.querySelector('#deviceSelect')?.focus();}if(e.target.dataset.mode){state[e.target.dataset.mode]=e.target.value;toast('デモ内の設定を変更しました');}});
document.querySelector('#detail').addEventListener('click',e=>{if(e.target.closest('.close'))e.currentTarget.close();if(e.target.id==='confirmReplace'){state.replaced[state.device]=true;e.currentTarget.close();render();toast('交換を記録しました');}});
document.querySelector('.skip').addEventListener('click',e=>{e.preventDefault();const main=document.querySelector('#content');main.setAttribute('tabindex','-1');main.focus();});
window.addEventListener('hashchange',()=>{render();window.scrollTo(0,0);});render();
